sudo: required

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - truffle version
  - docker run -d -p 7545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0

script:
  - npm run lint
  - npm run build-test
