sudo: required

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - truffle version
  - cd utils
  - docker build -f Dockerfile.contracts -t contracts .

script:
  - docker run -p 7545:7545 contracts /bin/sh /smart-contracts/utils/run_test.sh
